kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-pane
    image: kindest/node:v1.33.1
  - role: worker
    image: kindest/node:v1.33.1
  - role: worker
    image: kindest/node:v1.33.1