kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: myingress
  namespace: nginx-ns
  nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
   - http:
      paths:
      - pathType: Prefix
        path: /gameapp
        backend:
          service:
            name: first-app
            port: 
              number: 80
      - pathType: Prefix
        path: /site
        backend:
          service:
            name: site-app-service
            port: 
              number: 80
